fix: Update Roles API calls to async versions for Meteor 3.0
- Changed Roles.addUsersToRoles to await Roles.addUsersToRolesAsync
- Changed Roles.removeUsersFromRoles to await Roles.removeUsersFromRolesAsync
- Changed Roles.createRole to await Roles.createRoleAsync with {unlessExists: true}
- Refactored roleAdd function to use async/await with for...of instead of _.each

Fixes TypeError: Roles.addUsersToRoles is not a function